name: Lint and test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup V
        run: |
          git clone --depth=1 https://github.com/vlang/v /tmp/v && cd /tmp/v && make
          /tmp/v/v symlink

      - name: Run tests
        run: |
          v fmt -verify .
          v vet -v -W -I -F -r .
          v missdoc -r --verify .
          v -stats test .
